language: python
env:
  global:
  - ISTRAVIS=True
  - PYTHONPATH=.
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- tests/run_tests
deploy:
  provider: pypi
  user: friskby
  password:
    secure: j3kcKU7h7bd+AeYX3DCt5tQSfkIfzRUlMNLTLhh1S/OFISsy84MurKZBwJXRkQNUErnkYYN2vwj+CFP87Uq4RBDDTqN855VyGDB8lHayDRB1OBdypoLo86XXByN3ZQh+BDVRO3svRPjv5UkfF1cBNdgjxxPGQSGvHZ2XVce3GqCoMVLg8xfOFZajzh8WAjCkj/CngqSkqrQc4fM9hpavrzH4Ws8HsCQAR3vhpXkXMNclAzcyClBm+BM1mmWYgf8qiq/HwmI/ALExb6gLDS1tMnCPN3gqLfd80m9oBRvR+NDPWlL4D10XntnSXuyvdEu/FTeWjNslczMRS5MJX33l8PgEhgv9PJJpx76Fwt2stuevJtQXaXnPQzRCLY4T7L0Qu0jdSvyN0ZMDsJpfDxH+6QRl2Vn3SFMO2Z9VXi1jeUe2XVPRsusYWBZLQi2fzllflYP8EN1rzKjqgUbtI2EQpFtiEfmZiJBaWVfQN3BVSsxF7/JRyYiAV0YnwIG2Hya9tifUSEwtuxarMo4jgx9Aws4QwVV7n4w9DJlpjh1JKWm8jI9x3YDlaIQ4FrrXvOq2fFufUR9Vi2R13TQPyOkJvxtHon5onySsHq5ufwjPep5KAX2SwQrwMgQYWFNoyMVRwKVzUNuJSMGWrbq5BbrQ4PUgLA22YaaA2WJursFCIQk=
  on:
    branch: master
    distributions: sdist bdist_wheel
